spring:
  profiles: default

  flyway:
    enabled: true
    ignore-missing-migrations: true
    locations: classpath:/migration
    baseline-on-migrate: true
    baseline-description: Flyway Scripts
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

    # mail server config to send emails
  mail:
    host: smtp.gmail.com
    port: 587
    username: work.schedule.test
    password: test13580
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# security key
security:
  secretKey: Secret-Key

# URL to confirm email
email:
  sender:
    settings:
      url-to-confirm-page: "http://localhost:8081/rest/confirm"
      from-email: blablabla@mail.mmm
      subject: "Do not replay. Verify your email"
      template: creat_account_email

